### ISSUE TITLE
README and license file please

### ISSUE THREAD

**Issue by BigEd** [hoglet67/CoPro6502#1]
Dave, please could you add a minimal README with link to the matchbox copro discussion on stardot, and a license file too?  (Perhaps update the project description to mention LX9 too?)
Thanks!

**Comment by hoglet67** [comment]
Done.

Please feel free to send me any additional text you think should be present.

**Comment by BigEd** [comment]
Thanks!  The project description still reads
"BBC Micro 6502/Z80/6809 Co Processors for the GODIL GOP X3S200"
I wonder if you could squeeze in a reference to Matchbox and/or LX9?
Edit: oops, hit the Close button!

**Comment by hoglet67** [comment]
Updated project description

**Comment by BigEd** [comment]
Thanks!
